#include "GLSupport.h"

PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D = nullptr;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D = nullptr;
PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;
PFNGLCLIENTACTIVETEXTUREPROC glClientActiveTexture = nullptr;
PFNGLGETSTRINGIPROC glGetStringi = nullptr;
PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback = nullptr;

PFNWGLCREATEBUFFERREGIONARBPROC wglCreateBufferRegionARB = nullptr;
PFNWGLDELETEBUFFERREGIONARBPROC wglDeleteBufferRegionARB = nullptr;
PFNWGLSAVEBUFFERREGIONARBPROC wglSaveBufferRegionARB = nullptr;
PFNWGLRESTOREBUFFERREGIONARBPROC wglRestoreBufferRegionARB = nullptr;

PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB = nullptr;
PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB = nullptr;

PFNWGLGETPIXELFORMATATTRIBIVARBPROC wglGetPixelFormatAttribivARB = nullptr;
PFNWGLGETPIXELFORMATATTRIBFVARBPROC wglGetPixelFormatAttribfvARB = nullptr;
PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB = nullptr;

PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = nullptr;
PFNWGLGETSWAPINTERVALEXTPROC wglGetSwapIntervalEXT = nullptr;

#define TRY_LOAD(type, name) name = reinterpret_cast<type>(wglGetProcAddress(#name))

void InitGLSupport(void) {
	TRY_LOAD(PFNGLCOMPRESSEDTEXIMAGE2DPROC, glCompressedTexImage2D);
	TRY_LOAD(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC, glCompressedTexSubImage2D);
	TRY_LOAD(PFNGLACTIVETEXTUREPROC, glActiveTexture);
	TRY_LOAD(PFNGLCLIENTACTIVETEXTUREPROC, glClientActiveTexture);
	TRY_LOAD(PFNGLGETSTRINGIPROC, glGetStringi);
	TRY_LOAD(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback);

	TRY_LOAD(PFNWGLCREATEBUFFERREGIONARBPROC, wglCreateBufferRegionARB);
	TRY_LOAD(PFNWGLDELETEBUFFERREGIONARBPROC, wglDeleteBufferRegionARB);
	TRY_LOAD(PFNWGLSAVEBUFFERREGIONARBPROC, wglSaveBufferRegionARB);
	TRY_LOAD(PFNWGLRESTOREBUFFERREGIONARBPROC, wglRestoreBufferRegionARB);

	TRY_LOAD(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB);
	TRY_LOAD(PFNWGLGETEXTENSIONSSTRINGARBPROC, wglGetExtensionsStringARB);

	TRY_LOAD(PFNWGLGETPIXELFORMATATTRIBIVARBPROC, wglGetPixelFormatAttribivARB);
	TRY_LOAD(PFNWGLGETPIXELFORMATATTRIBFVARBPROC, wglGetPixelFormatAttribfvARB);
	TRY_LOAD(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);

	TRY_LOAD(PFNWGLSWAPINTERVALEXTPROC, wglSwapIntervalEXT);
	TRY_LOAD(PFNWGLGETSWAPINTERVALEXTPROC, wglGetSwapIntervalEXT);
}