#include "GLSupport.h"

PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D = nullptr;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D = nullptr;
PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;
PFNGLCLIENTACTIVETEXTUREPROC glClientActiveTexture = nullptr;
PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback = nullptr;

PFNWGLCREATEBUFFERREGIONARBPROC wglCreateBufferRegionARB = nullptr;
PFNWGLDELETEBUFFERREGIONARBPROC wglDeleteBufferRegionARB = nullptr;
PFNWGLSAVEBUFFERREGIONARBPROC wglSaveBufferRegionARB = nullptr;
PFNWGLRESTOREBUFFERREGIONARBPROC wglRestoreBufferRegionARB = nullptr;

#define TRY_LOAD(type, name) name = reinterpret_cast<type>(wglGetProcAddress(#name))

void InitGLSupport(void) {
	TRY_LOAD(PFNGLCOMPRESSEDTEXIMAGE2DPROC, glCompressedTexImage2D);
	TRY_LOAD(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC, glCompressedTexSubImage2D);
	TRY_LOAD(PFNGLACTIVETEXTUREPROC, glActiveTexture);
	TRY_LOAD(PFNGLCLIENTACTIVETEXTUREPROC, glClientActiveTexture);
	TRY_LOAD(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback);

	TRY_LOAD(PFNWGLCREATEBUFFERREGIONARBPROC, wglCreateBufferRegionARB);
	TRY_LOAD(PFNWGLDELETEBUFFERREGIONARBPROC, wglDeleteBufferRegionARB);
	TRY_LOAD(PFNWGLSAVEBUFFERREGIONARBPROC, wglSaveBufferRegionARB);
	TRY_LOAD(PFNWGLRESTOREBUFFERREGIONARBPROC, wglRestoreBufferRegionARB);
}